services:
  rmu-mongo:
    image: mongo:8.0
    hostname: rmu-mongo
    container_name: rmu-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - rmu-mongo-data:/data/db
    networks:
      - rmu-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rmu-postgres:
    image: postgres:16
    hostname: rmu-postgres
    container_name: rmu-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_KEYCLOAK}
    networks:
      - rmu-network
    volumes:
      - rmu-postgres-data:/var/lib/postgresql/data

  rmu-keycloak:
    image: quay.io/keycloak/keycloak:26.3
    hostname: rmu-keycloak
    container_name: rmu-keycloak
    command:
      - start
      - --features=scripts
      - --http-enabled=true
      - --hostname=localhost
    ports:
      - "8090:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: rmu-postgres
      KC_DB_URL_DATABASE: ${POSTGRES_DB_KEYCLOAK}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: localhost
      KC_LOG_LEVEL: INFO
    volumes:
      - rmu-keycloak-data:/opt/keycloak/data
    networks:
      - rmu-network

  rmu-kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: rmu-kafka-broker
    container_name: rmu-kafka-broker
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://rmu-kafka-broker:9092,PLAINTEXT_HOST://localhost:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@rmu-kafka-broker:9094'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: localhost
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - rmu-kafka-data:/var/lib/kafka/data
    networks:
      - rmu-network
    healthcheck:
      test: ["CMD-SHELL", "bash -c '>/dev/tcp/localhost/9092 && echo ok || exit 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: rmu-kafka-ui
    depends_on:
      - rmu-kafka
    ports:
      - "8091:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: rmu-kafka-broker:9092
      KAFKA_CLUSTERS_0_READONLY: false
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: ${KAFKA_UI_USER}
      SPRING_SECURITY_USER_PASSWORD: ${KAFKA_UI_PASSWORD}
    networks:
      - rmu-network

  rmu-api-core:
    image: labcabrera/rmu-api-core:latest
    container_name: rmu-api-core
    depends_on:
      rmu-mongo:
        condition: service_healthy
      rmu-kafka:
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      RMU_MONGO_CORE_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@rmu-mongo:27017/rmu-core?authSource=admin
      RMU_IAM_BASE_URL: http://rmu-keycloak:8080
      RMU_IAM_JWK_URI: http://rmu-keycloak:8080/realms/rmu-local/protocol/openid-connect/certs
      RMU_IAM_TOKEN_URI: http://rmu-keycloak:8080/realms/rmu-local/protocol/openid-connect/token
      RMU_IAM_REALM: ${KEYCLOAK_REALM}
      RMU_IAM_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      RMU_IAM_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      RMU_KAFKA_CLIENT_ID: rmu-api-core
      RMU_KAFKA_BROKERS: rmu-kafka-broker:9092
      RMU_KAFKA_PARTITION_COUNT: '1'
    networks:
      - rmu-network

  rmu-api-strategic:
    image: labcabrera/rmu-api-strategic:latest
    container_name: rmu-api-strategic
    depends_on:
      rmu-mongo:
        condition: service_healthy
      rmu-kafka:
        condition: service_healthy
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      RMU_MONGO_STRATEGIC_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@rmu-mongo:27017/rmu-strategic?authSource=admin
      RMU_IAM_BASE_URL: http://rmu-keycloak:8080
      RMU_IAM_JWK_URI: http://rmu-keycloak:8080/realms/rmu-local/protocol/openid-connect/certs
      RMU_IAM_TOKEN_URI: http://rmu-keycloak:8080/realms/rmu-local/protocol/openid-connect/token
      RMU_IAM_REALM: rmu-local
      RMU_IAM_CLIENT_ID: rmu-client
      RMU_IAM_CLIENT_SECRET: 1tUzPc24SYJMPpX37g2eymEoS9C3Ttzw
      RMU_KAFKA_CLIENT_ID: rmu-api-strategic
      RMU_KAFKA_BROKERS: rmu-kafka-broker:9092
      RMU_KAFKA_PARTITION_COUNT: '1'
      RMU_API_CORE_URI: http://rmu-api-core:3001
      RMU_API_ITEMS_URI: http://rmu-api-items:3004
    networks:
      - rmu-network

  rmu-api-tactical:
    image: labcabrera/rmu-api-tactical:latest
    container_name: rmu-api-tactical
    depends_on:
      rmu-mongo:
        condition: service_healthy
      rmu-kafka:
        condition: service_healthy
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      RMU_MONGO_TACTICAL_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@rmu-mongo:27017/rmu-tactical?authSource=admin
      RMU_IAM_BASE_URL: http://rmu-keycloak:8080
      RMU_IAM_JWK_URI: http://rmu-keycloak:8080/realms/rmu-local/protocol/openid-connect/certs
      RMU_IAM_TOKEN_URI: http://rmu-keycloak:8080/realms/rmu-local/protocol/openid-connect/token
      RMU_IAM_REALM: rmu-local
      RMU_IAM_CLIENT_ID: rmu-client
      RMU_IAM_CLIENT_SECRET: 1tUzPc24SYJMPpX37g2eymEoS9C3Ttzw
      RMU_KAFKA_CLIENT_ID: rmu-api-tactical
      RMU_KAFKA_BROKERS: rmu-kafka-broker:9092
      RMU_KAFKA_PARTITION_COUNT: '1'
      RMU_API_CORE_URI: http://rmu-api-core:3001
      RMU_API_STRATEGIC_URI: http://rmu-api-strategic:3002
      RMU_API_ITEMS_URI: http://rmu-api-items:3004
      RMU_API_ATTACK_URI: http://rmu-api-attack:3005
    networks:
      - rmu-network

  rmu-api-attack-tables:
    image: labcabrera/rmu-api-attack-tables:latest
    container_name: rmu-api-attack-tables
    depends_on:
      rmu-mongo:
        condition: service_healthy
    ports:
      - "3005:3005"
    environment:
      PORT: 3005
    networks:
      - rmu-network

  rmu-api-attack:
    image: labcabrera/rmu-api-attack:latest
    container_name: rmu-api-attack
    depends_on:
      rmu-mongo:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      RMU_MONGO_ATTACK_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@rmu-mongo:27017/rmu-attack?authSource=admin
      RMU_API_ATTACK_TABLES_URL: http://rmu-api-attack-tables:3005/v1
    networks:
      - rmu-network

  rmu-api-items:
    image: labcabrera/rmu-api-items:latest
    container_name: rmu-api-items
    depends_on:
      rmu-mongo:
        condition: service_healthy
      rmu-kafka:
        condition: service_healthy
    ports:
      - "3006:3006"
    environment:
      PORT: 3006
      RMU_MONGO_ITEMS_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@rmu-mongo:27017/rmu-items?authSource=admin
      RMU_IAM_JWK_URI: http://rmu-keycloak:8080/realms/rmu-local/protocol/openid-connect/certs
      RMU_KAFKA_BROKERS: rmu-kafka-broker:9092
      RMU_KAFKA_CLIENT_ID: rmu-api-items
      RMU_KAFKA_CONSUMER_GROUP_ID: rmu-api-items-consumer
      RMU_KAFKA_DEFAULT_PARTITIONS: 1
    networks:
      - rmu-network

volumes:
  rmu-mongo-data:
    driver: local
  rmu-keycloak-data:
    driver: local
  rmu-postgres-data:
    driver: local
  rmu-kafka-data:
    driver: local

networks:
  rmu-network:
    external: true
