apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rmu-fe-tactical
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-local
  source:
    path: k8s
    repoURL: https://github.com/labcabrera/rmu-fe-tactical
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
