@startuml c4-context
title RMU Engine Context Diagram

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_LEFT_RIGHT()

UpdateElementStyle(person, $bgColor="#2b4a74ff")
UpdateElementStyle(system, $bgColor="#4373b1ff")
UpdateElementStyle(external_system, $bgColor="#96b6beff")
UpdateElementStyle(boundary, $bgColor="#d1dcdfff")

Person(user, "User")

Boundary(frontend, "RMU Engine Microfrontends") {
    System(rmu_mfe_shell, "MFE Shell", "React")
    System(rmu_mfe_core, "MFE Core", "React")
    System(rmu_mfe_strategic, "MFE Strategic", "React")
    System(rmu_mfe_tactical, "MFE Tactical", "React")
    System(rmu_mfe_items, "MFE Items", "React")
    System(rmu_mfe_npc, "MFE NPCs", "React")
    System(rmu_mfe_spells, "MFE SPells", "React")
    System(rmu_react_shared_lib, "React Shared Lib", "React + MUI")
    System(rmu_mfe_assets, "MFE Assets", "Static files: locales, images...")
}

Boundary(apis, "RMU Engine APIs") {
    System(rmu_api_users, "Users API", "NestJS")
    System(rmu_api_core, "Core API", "NestJS")
    System(rmu_api_strategic, "Strategic API", "NestJS")
    System(rmu_api_tactical, "Tactical API", "NestJS")
    System(rmu_api_npc, "NPC API", "NestJS")
    System(rmu_api_npc_names, "NPC Names API", "Node.js")
    System(rmu_api_attack, "Attack API", "Python")
    System(rmu_api_spells, "Spell API", "NestJS")
    System(rmu_api_items, "Items API", "NestJS")
    System(rmu_api_attack_tables, "Attack Tables API", "Node.js")
}

Boundary(infrastructure, "Infrastructure") {
    System_Ext(mongodb, "MongoDB", "8.x")
    System_Ext(keycloak, "Keycloak", "26.x")
    System_Ext(kafka, "Kafka", "3.4.x")
    System_Ext(postgresql, "PostgreSQL", "16.x")
}

Rel(user, rmu_mfe_shell, "Navigate", "HTTP")
Rel(user, keycloak, "Login", "HTTP")

Rel(rmu_mfe_shell, rmu_mfe_core, "Federation", "OIDC")
Rel(rmu_mfe_shell, rmu_mfe_strategic, "Federation", "Webpack")
Rel(rmu_mfe_shell, rmu_mfe_tactical, "Federation", "Webpack")
Rel(rmu_mfe_shell, rmu_mfe_items, "Read profile", "OIDC")
Rel(rmu_mfe_shell, rmu_mfe_npc, "Federation", "Webpack")
Rel(rmu_mfe_shell, rmu_mfe_spells, "Federation", "Webpack")

Rel(rmu_mfe_shell, rmu_api_users, "Read profile", "OIDC")
Rel(rmu_mfe_shell, keycloak, "Authenticate user", "OIDC")
Rel(rmu_mfe_shell, rmu_mfe_assets, "Load static content", "HTTP")

Rel(rmu_mfe_core, rmu_api_core, "", "HTTP")

Rel(rmu_mfe_strategic, rmu_api_strategic, "", "HTTP")
Rel(rmu_mfe_strategic, rmu_api_npc_names, "", "HTTP")

Rel(rmu_mfe_tactical, rmu_api_tactical, "", "HTTP")

Rel(rmu_api_users, keycloak, "Read user info", "OIDC")

Rel(rmu_mfe_npc, rmu_api_npc, "", "HTTP")

Rel(rmu_mfe_items, rmu_api_items, "", "HTTP")

Rel(rmu_mfe_spells, rmu_api_spells, "", "HTTP")

Rel(rmu_api_tactical, rmu_api_attack, "Manage attacks", "HTTP")

Rel(rmu_api_attack, rmu_api_attack_tables, "Read tables", "HTTP")

Rel(keycloak, postgresql, "", "")

SHOW_LEGEND()

@enduml
